apiVersion: v2
name: rental-platform
description: Платформа для управления арендой оборудования
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: vault
    version: "0.30.0"
    repository: "https://helm.releases.hashicorp.com"
    condition: vault.enabled

#  - name: bank-vaults
#    version: "1.20.6"
#    repository: "oci://ghcr.io/bank-vaults/helm-charts"
#    condition: vault.mutatingWebhook.enabled

  - name: kube-prometheus-stack
    version: "45.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled

  - name: argo-rollouts
    version: "2.32.0"
    repository: "https://argoproj.github.io/argo-helm"
    condition: rollouts.enabled
