{{- if .Values.docService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docService
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.docService.replicaCount }}
  selector:
    matchLabels:
      app: docService
  template:
    metadata:
      annotations:
        {{- if .Values.docService.vault.enabled }}
        vault.security.banzaicloud.io/vault-addr: "http://vault:8200"
        vault.security.banzaicloud.io/vault-path: "secret/rental-platform"
        vault.security.banzaicloud.io/vault-role: "rental-platform"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        {{- end }}
      labels:
        app: docService
    spec:
      containers:
      - name: docService
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.docService.image.repository }}:{{ .Values.docService.image.tag }}"
        ports:
        - containerPort: 8081
        env:
        - name: APPLICATION_PORT
          value: "8081"        
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        {{- with .Values.docService.resources }}
        resources:
          {{ toYaml . | nindent 10 }}
        {{- end }}
{{- end }}